import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Key Rush",
  description: "Generated by Js Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="scrollbar-thin scrollbar-track-neutral-700 scrollbar-thumb-[#ff3434]">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
